batchsize: 32
seed: 1
max_iteration: 50000
report_freq: 1000
model_snapshot_freq: 10000
manager_snapshot_freq: 50000
num_workers: 2
T_cond: 2
T_pred: 1
lr: 0.0003

train_data:
  fn: ./datasets/seq_mnist.py
  name: SequentialMNIST
  args:
    root: /tmp/datasets/MNIST
    train: True
    T: 3
    max_T: 9
    max_angle_velocity_ratio: [-0.5, 0.5]
    max_color_velocity_ratio: [-0.5, 0.5]
    only_use_digit4: True

model:
  fn: ./models/seqae.py
  name: SeqAENeuralMLatentPredict
  args:
    dim_m: 256
    dim_a: 16
    ch_x: 3
    k: 2.
    loss_reconst_coeff: 0.0
    loss_pred_coeff: 1.0
    loss_latent_coeff: 0.0
    normalize: True




training_loop:
  fn: ./training_loops.py
  name: loop_seqmodel
  args:
    lr_decay_iter: 40000
    reconst_iter: 50000



